# Worksheet 1

## Question 1

In [25]:
import numpy as np

In [26]:
random_arr = np.random.randint(1,high=100,size=(5,5))
print(random_arr)

[[57 57 11 12 31]
 [90 98 56 31 48]
 [99 48 36 64 25]
 [56 59 17 36 58]
 [93 83 48 13 42]]


### Part A

In [27]:
middle_element = random_arr[2][2]
print(middle_element)

36


### Part B

In [28]:
row_mean = np.mean(random_arr, axis = 1,dtype=np.float64)
print(row_mean)

[33.6 64.6 54.4 45.2 55.8]


### Part C

In [29]:
mean = np.mean(random_arr,dtype=np.float64)
print(mean)

50.72


In [30]:
mask = random_arr > mean
mean_arr = random_arr[mask]
print(mean_arr)

[57 57 90 98 56 99 64 56 59 58 93 83]


### Part D

In [31]:
def spiral_order(arr):
    row = len(arr)
    col = len(arr[0])
    ans = []
    top ,bottom ,left ,right = 0, row, 0, col
    while top < bottom and left < right : 

        # top row
        for i in range (left,right):
            ans.append(arr[top][i])
        top += 1

        # right column
        for i in range (top,bottom):
            ans.append(arr[i][right - 1])
        right -= 1

        # bottom row
        if top < bottom :
            for i in range (right - 1, left - 1, -1):
                ans.append(arr[bottom - 1][i])
            bottom -= 1

        #left row
        if left < right :
            for i in range (bottom - 1, top - 1, -1):
                ans.append(arr[i][left])
            left += 1
            
    return ans

In [32]:
spiral_list = spiral_order(random_arr.tolist())
spiral_list
print(spiral_list)

[57, 57, 11, 12, 31, 48, 25, 58, 42, 13, 48, 83, 93, 56, 99, 90, 98, 56, 31, 64, 36, 17, 59, 48, 36]


## Question 2